POST http://localhost:5000/newCollection
Content-Type: application/json

{
    "collectionName":"recipes"
}


###
post http://localhost:5000/recipes
Content-Type: application/json

{
    "collectionName":"recipes",
    "data":[{
  "title": "אגווט׳",
  "name": "יעקב קסה",
  "category": "Milk",
  "Ingredients": "חלב.\r\n8 גביעי שמנת.\r\n4 גביעי אשל.",
  "Instructions": "להרתיח את החלב.\nואז אחר כך לשפוך את כל הגביעי שמנת והאשל.",
  "Nots": "להרתיח על אש נמוכה. \nלמשך שעה וחצי.\nצריך בצד סלטים ולחם(דבו)\nבתיאבון!.",
  "src": "d132fb4694c07c3817c197821d7cf1f1",
  "comments": [],
  "id": "7a9cfb81-dae4-4a8c-a043-81be6c67bf36",
  "localId": "BB60Pu95PLSu945LUSPD7VoPeLt1"
},{
  "title": "דבו (לחם)",
  "name": "יעקב קסה",
  "category": "Vegeterian",
  "Ingredients": "קילו קמח.\r\n3 כוסות סולת.\r\n3-4 כוסות מים בהדרגה.\r\n1 ורבע כף שמרים.\r\nכף סוכר.\r\nכפית מלח.\r\n2 כפות שמן",
  "Instructions": "מערבבים את השמרים והסוכר במים.\r\nהקמח(מנופא) ומעל שמים את המלח את המים בהדרגה לשים עד ליצירת בצק רך ודביק לא מימי מדי מכסים בניילון ומנחים להתפחה...מורדים את ההתפחה ומעבירים לסיר ג׳חנון מרופד בנייר אפיה ומשומן מעט לתת לבצק עוד כמה דקות לתפוח בתוך הסיר.. שמים נייר אפיה משומן מעל וסוגרים את הסיר שמים על הגז מחבת ועליה את הסיר על אש נמוכה ..אחרי 20 ד בערך פותחים רואים שהחלק העליון בשל הופכים יחד עם מכסה סגור לשיש ומרמים בעדינות את נייר האפיה התחתון ומחזירים שוב להשחמה של החלק התחתון...למי שאוהבת ניתן להוסיף לתערובת בשביל הטעם והריח קצח גרגירים או חילבה גרגרים עינת חנניה...בהצלחה ",
  "Nots": "בתיאבון!.",
  "src": "95621382167fd7059583c080c5ad6909",
  "comments": [],
  "id": "f908b09b-853c-4efe-b50a-f7f22d84c6db",
  "localId": "BB60Pu95PLSu945LUSPD7VoPeLt1"
},{
  "title": "אינג׳רה",
  "name": "יעקב קסה",
  "category": "Vegeterian",
  "Ingredients": "קילו קמח טף.\r\nמים.",
  "Instructions": "1. מניחים בקערה את קמח הטף ומוסיפים מים קרים בהדרגה תוך כדי בחישה.\r\n2. לשים עד קבלת עיסה אחידה לא רכה מדי ולא קשה מדי.\r\nמכסים במגבת לחה ומניחים בצד למשך לילה שלם.\r\n3. למחרת, לאחר שהבצק תפח והחמיץ מעט, מדללים אותו בעזרת מעט מים קרים ולשים שוב. מוסיפים כ- 3/4 ליטר מים רותחים ובוחשים עד קבלת בלילה דלילה שדומה במרקמה לבלילת פנקייק. במידה והמים הרותחים לא מספיקים לתהליך, מוסיפים בהדרגה עוד מים קרים וממשיכים לבחוש עד שלא נותרים גושים.\r\n4. מכסים שוב ומניחים בצד (למשך כ- 6 שעות) עד שהבצק מבעבע ומוציא קצף לבן מלמעלה.\r\n5. לבישול האינג'ירה: מחממים מחבת עבה (עדיף טפלון) על אש גבוהה.\r\n6. בעזרת צמר גפן מושחים את המחבת במעט מאוד שמן.\r\nבעזרת מצקת יוצקים מהבלילה על המחבת (בדומה להכנת פנקייק).\r\n7. כשרואים שהבצק מתחיל לבעבע, מכסים את המחבת עם מכסה למשך כדקה. כשהבצק בושל, מוציאים ומניחים בצד וחוזרים על התהליך מההתחלה.",
  "Nots": "בתיאבון!.",
  "src": "ab663b62920f498315d7e3d6349bd244",
  "comments": [],
  "id": "26cc3866-d848-481d-a8f2-c6efd0d41ad7",
  "localId": "BB60Pu95PLSu945LUSPD7VoPeLt1"
},{
  "title": "קק",
  "name": "יעקב קסה",
  "category": "Vegeterian",
  "Ingredients": "חצי קילו אפונה יבשה\r\n2 שיני שום כתושות\r\nבצל לבן קצוץ\r\nכפית ג'ינג'ר טחון\r\nתערובת תבלינים: חצי כפית מלח, רבע כפית הל, רבע כפית ציפורן, רבע כפית קצח, חצי כפית פלפל שחור, רבע כפית קמם (תבלין אתיופי)",
  "Instructions": "1. שוטפים את האפונה היבשה ומשרים למשך לילה בקערה עם מים פושרים.\r\n\r\n2. לאחר ההשריה, מטגנים בצל, שום  וג'ינג'ר טחון (לפי הטעם) בסיר.\r\n\r\n3. מוסיפים חצי קילו אפונה ומוסיפים כוס וחצי מים (אם יש צורך, אפשר להוסיף עוד קצת מים).\r\n\r\n4. מוסיפים את תערובת התבלינים, ומבשלים על אש קטנה למשך כשעה, עד שהתבשיל מקבל סמיכות ורכות ומוכן.\r\n\r\n5. אפשר לטחון קלות עם בלנדר מוט או להגיש כפי שהוא.\r\n\r\nעברו לתצוגת גלריה\r\n",
  "Nots": "בתיאבון!.",
  "src": "2af1a2b9c27869880b9a8fc242eb923b",
  "comments": [],
  "id": "b4602ad7-e307-4de3-ab2e-161beddb3bfc",
  "localId": "BB60Pu95PLSu945LUSPD7VoPeLt1"
},{
  "title": "סיגה ווט",
  "name": "יעקב קסה",
  "category": "Meat",
  "Ingredients": "1 בצל גדול\r\n4 כפות שמן\r\n3 כפות צ'ואו (תערובת תבלינים אתיופית)\r\nבשר אוסובוקו / אסאדו - מומלץ טרי\r\nתבלינים: מלח, פלפל, פפריקה מתוקה וחריפה\r\n3 כוסות מים\r\n8 שיני שום",
  "Instructions": "יש לחתוך בצל 1 גדול ולטגן עם 4 כפות שמן עד להזהבה.\r\n\r\nיש להוסיף 3 כפות צ'או (תערובת תבלינים אתיופית).\r\n\r\nיש לבשל מס' דקות ולאחר מכן להוסיף את הבשר (אוסבקו ואסאדו).\r\n\r\nלאחר חצי שעה בישול מוסיפים 3 כוסות מים רותחים ומתבלים: מלח פלפל שחור פפריקה מתוקה ופפריקה חריפה.\r\n\r\nיש להוסיף כ- 8 שיני שום (חצי חתוך חצי כתוש) ולתת לטעמים להיספג בבישול של עוד שעה.",
  "Nots": "בתיאבון!.",
  "src": "2d91805135e9249dfb5cd20bad0e76e4",
  "comments": [],
  "id": "74700234-e41e-4bb3-9165-fdd2d003bb91",
  "localId": "BB60Pu95PLSu945LUSPD7VoPeLt1"
},{
  "title": "סיגה ווט",
  "name": "יעקב קסה",
  "category": "Meat",
  "Ingredients": "חצי כוס מים\r\n2 כפות גדושות של צ'ואו (עיסת תבלינים חריפה - אתיופית)\r\n2 קילו כבש חתוך לקוביות של 2 ס\"מ - מומלץ להוסיף צלעות\r\nחצי כפית מלח.\r\nחצי כפית קמם (תערובת תבלינים אתיופית).",
  "Instructions": "לוקחים סיר רחב ועמוק ומרתיחים בתוכו חצי כוס מים. מוסיפים 2 כפות גדושות של צ'או מערבבים ומביאים לרתיחה (פותחים את הצ'או). \r\nמוסיפים את הבשר מערבבים ומבשלים כשעה (מוסיפים מיד במידת הצורך). בסיום ההכנה מוסיפים רבע כפית מלח ו- חצי כפית קמם.",
  "Nots": "מומלץ להגיש את המנה בתוספת אינג'רה, עשויה מטף.\r\nבתיאבון!.",
  "src": "855451f56a6f532f16cffc30d7a018bd",
  "comments": [
    "טעים !!"
  ],
  "id": "3d91a0bd-1ca8-4c65-8024-f5233652daac",
  "localId": "BB60Pu95PLSu945LUSPD7VoPeLt1"
},{
  "title": "מיסיר אליצ׳ה",
  "name": "יעקב קסה",
  "category": "Vegeterian",
  "Ingredients": "חצי קילו עדשים כתומות\r\n2 שיני שום כתושות\r\nבצל לבן קצוץ\r\nכפית ג'ינג'ר טחון\r\nתערובת תבלינים: חצי כפית מלח, רבע כפית הל, רבע כפית ציפורן, רבע כפית קצח, חצי כפית פלפל שחור, רבע כפית קמם (תבלין אתיופי)",
  "Instructions": "1. שוטפים את העדשים ומשרים למשך שעה בקערה עם מים פושרים.\r\n\r\n2. לאחר ההשריה, מטגנים בצל, שום  וג'ינג'ר טחון (לפי הטעם) בסיר.\r\n\r\n3. מוסיפים חצי קילו עדשים ומוסיפים כוס וחצי מים.\r\n\r\n4. מוסיפים את תערובת התבלינים, ומבשלים על אש קטנה למשך שעה עד שהתבשיל מקבל סמיכות. אפשר להוסיף מעט מים כדי לשלוט במרקם הרצוי.",
  "Nots": "מומלץ להגיש את המנה בתוספת אינג'רה, עשויה מטף.\r\nבתיאבון!.",
  "src": "891adb429bd495d8727117d94d2be995",
  "comments": [],
  "id": "313099c2-09e6-4804-8407-7193d822788f",
  "localId": "BB60Pu95PLSu945LUSPD7VoPeLt1"
},{
  "title": "קולו",
  "name": "המטבח של אמא",
  "category": "Vegeterian",
  "Ingredients": "גרעיני שעורה.\r\nניתן להוסיף  בוטנים, אגוזים או זרעים אחרים.",
  "Instructions": "יש לקלות על אש נמוכה, למשך 15 דק׳.\r\n",
  "Nots": "מומלץ להגיש עם משקה.\r\nבתאבון!",
  "src": "9914d08188571226a0838b6bfefc03a4",
  "comments": [],
  "id": "7a719229-bc58-41a3-9217-81b61f7cd4d2",
  "localId": "3s3ciyopuifSoliJeglZLzhcrdz1"
}]
}
###
GET http://localhost:5000/recipes
###
GET http://localhost:5000/categories/milk
###

GET http://localhost:5000/recipe/1f486691-d630-4109-b3b9-4390f0a0937e
###

PATCH http://localhost:5000/recipe/55f95e47-da89-457a-b884-e030d56b6145
Content-Type: application/json

{
    "comments":"see me???",
    "name":"yakov kassa"
}
###
Get http://localhost:5000/image/b13c28030339b7ab1e607883e155e2c5
###

Get http://localhost:5000/recipe/user/3s3ciyopuifSoliJeglZLzhcrdz1
###
DELETE http://localhost:5000/recipe/e2106012-a5b9-4504-8e65-61ec1c2a8e59
###